services:

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend/static:/app/static
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static:/app/static
      - ./frontend/dist:/usr/share/nginx/html
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
