services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    volumes:
      - backend-static:/app/static
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - backend-static:/app/static
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  backend-static:
